import type { CSSProperties } from 'react'

export const colors = {
  bg: '#0a0a0a',
  surface: '#111111',
  surfaceHover: '#1a1a1a',
  border: '#222222',
  borderActive: '#4ade80',
  text: '#f0f0f0',
  textMuted: '#666666',
  textSubtle: '#999999',
  primary: '#4ade80',
  primaryDark: '#22c55e',
  accent: '#4ade80',
  recording: '#ef4444',
  recordingDark: '#dc2626',
  success: '#4ade80',
  filled: '#0d1f12',
  filledBorder: '#166534',
  warning: '#f59e0b',
}

export const styles = {
  container: {
    minHeight: '100vh',
    background: colors.bg,
    color: colors.text,
    fontFamily:
      '"Noto Sans JP", "Hiragino Kaku Gothic ProN", -apple-system, BlinkMacSystemFont, sans-serif',
  },
  header: {
    borderBottom: `1px solid ${colors.border}`,
    background: colors.bg,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  headerInner: {
    maxWidth: 860,
    margin: '0 auto',
    padding: '14px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoArea: { display: 'flex', alignItems: 'center', gap: 10 },
  logoIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: colors.primary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 800,
    color: '#000',
  },
  title: { margin: 0, fontSize: 15, fontWeight: 700, letterSpacing: '-0.02em', color: colors.text },
  subtitle: { margin: 0, fontSize: 11, color: colors.textMuted, marginTop: 1 },
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 11,
    color: colors.primary,
    background: 'rgba(74, 222, 128, 0.08)',
    border: '1px solid rgba(74, 222, 128, 0.2)',
    padding: '5px 12px',
    borderRadius: 6,
    fontWeight: 600,
    letterSpacing: '0.02em',
    fontFamily: 'monospace',
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: colors.primary,
  },
  main: { maxWidth: 860, margin: '0 auto', padding: '24px 24px 80px' },
  statusBar: {
    padding: '10px 14px',
    background: 'rgba(74, 222, 128, 0.06)',
    border: '1px solid rgba(74, 222, 128, 0.15)',
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 16,
    color: colors.primary,
    fontWeight: 500,
    letterSpacing: '-0.01em',
  },
  errorBar: {
    padding: '10px 14px',
    background: 'rgba(239, 68, 68, 0.06)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 16,
    color: colors.recording,
    fontWeight: 500,
  },
  warningBar: {
    padding: '10px 14px',
    background: 'rgba(245, 158, 11, 0.06)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 16,
    color: colors.warning,
    lineHeight: 1.5,
  },
  modelPanel: {
    padding: '16px 20px',
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
  },
  progressBarOuter: {
    flex: 1,
    minWidth: 160,
    height: 3,
    borderRadius: 2,
    background: 'rgba(74, 222, 128, 0.12)',
    overflow: 'hidden',
  },
  progressBarInner: {
    height: '100%',
    background: colors.primary,
    transition: 'width 0.3s ease',
  },
  controlSection: { marginBottom: 20 },
  controlGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    gap: 8,
  },
  btn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 5,
    padding: '14px 8px',
    borderRadius: 8,
    border: '1px solid transparent',
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    transition: 'all 0.12s ease',
    position: 'relative',
    fontFamily: 'inherit',
    letterSpacing: '0.02em',
  },
  btnPrimary: {
    background: colors.primary,
    color: '#000',
    border: 'none',
  },
  btnRecording: {
    background: colors.recording,
    color: '#fff',
    border: 'none',
  },
  btnAccent: {
    background: 'rgba(74, 222, 128, 0.1)',
    color: colors.primary,
    border: '1px solid rgba(74, 222, 128, 0.25)',
  },
  btnGhost: {
    background: colors.surface,
    color: colors.textSubtle,
    border: `1px solid ${colors.border}`,
  },
  btnIcon: { fontSize: 20, lineHeight: 1 },
  pulse: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: '#fff',
  },
  transcriptSection: {
    background: colors.surface,
    borderRadius: 10,
    border: `1px solid ${colors.border}`,
    marginBottom: 20,
    padding: '16px 18px',
  },
  transcriptHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 8,
  },
  transcriptTextarea: {
    width: '100%',
    minHeight: 130,
    background: 'rgba(255,255,255,0.02)',
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    padding: '12px 14px',
    color: colors.text,
    fontSize: 14,
    lineHeight: 1.75,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical',
    boxSizing: 'border-box',
    transition: 'border-color 0.12s ease',
  },
  transcriptTextareaRecording: {
    borderColor: colors.recording,
    background: 'rgba(239, 68, 68, 0.03)',
  },
  liveBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.12em',
    color: colors.recording,
    background: 'rgba(239, 68, 68, 0.08)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    padding: '2px 8px',
    borderRadius: 5,
  },
  liveDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: colors.recording,
    animation: 'pulse-dot 1s ease-in-out infinite',
  },
  sectionToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    background: 'transparent',
    border: 'none',
    color: colors.text,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    fontWeight: 700,
    color: colors.textMuted,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
  },
  charCount: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: 500,
    fontFamily: 'monospace',
  },
  chevron: {
    fontSize: 10,
    color: colors.textMuted,
    transition: 'transform 0.2s ease',
  },
  transcriptBody: {
    padding: '0 18px 16px',
  },
  transcriptText: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.8,
    color: colors.text,
  },
  interimText: {
    color: colors.primary,
    opacity: 0.7,
  },
  placeholder: {
    margin: 0,
    fontSize: 13,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  formSection: { marginBottom: 24 },
  formTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    fontWeight: 700,
    color: colors.textMuted,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    marginBottom: 12,
  },
  fieldGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
  },
  fieldCard: {
    background: colors.surface,
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    padding: '14px 16px',
    cursor: 'pointer',
    transition: 'border-color 0.12s ease, background 0.12s ease',
  },
  fieldCardFull: { gridColumn: '1 / -1' },
  fieldCardFilled: {
    background: colors.filled,
    borderColor: 'rgba(74, 222, 128, 0.25)',
  },
  fieldHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    marginBottom: 7,
  },
  fieldIcon: { fontSize: 13, opacity: 0.7 },
  fieldLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.07em',
  },
  filledDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: colors.primary,
    marginLeft: 'auto',
  },
  fieldValue: {
    margin: 0,
    fontSize: 14,
    fontWeight: 500,
    color: colors.text,
    lineHeight: 1.5,
  },
  fieldPlaceholder: {
    margin: 0,
    fontSize: 13,
    color: 'rgba(102,102,102,0.6)',
  },
  fieldInput: {
    width: '100%',
    background: 'rgba(255,255,255,0.04)',
    border: `1px solid ${colors.borderActive}`,
    borderRadius: 6,
    padding: '7px 10px',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  fieldTextarea: {
    width: '100%',
    background: 'rgba(255,255,255,0.04)',
    border: `1px solid ${colors.borderActive}`,
    borderRadius: 6,
    padding: '8px 10px',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical',
    boxSizing: 'border-box',
    lineHeight: 1.6,
  },
  archSection: {
    background: colors.surface,
    borderRadius: 10,
    border: `1px solid ${colors.border}`,
    padding: 20,
  },
  archTitle: {
    margin: '0 0 16px',
    fontSize: 11,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
  },
  archFlow: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 4,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  archStep: {
    textAlign: 'center' as const,
    minWidth: 90,
    padding: '10px 8px',
  },
  archStepIcon: { fontSize: 24, marginBottom: 6 },
  archStepLabel: { fontSize: 12, fontWeight: 700, marginBottom: 2, color: colors.text },
  archStepTech: {
    fontSize: 10,
    color: colors.primary,
    fontWeight: 600,
    fontFamily: 'monospace',
  },
  archStepDesc: { fontSize: 10, color: colors.textMuted, marginTop: 3 },
  archArrow: {
    fontSize: 16,
    color: colors.border,
    marginTop: 18,
    padding: '0 4px',
  },
  archNote: {
    background: 'rgba(74, 222, 128, 0.04)',
    border: '1px solid rgba(74, 222, 128, 0.12)',
    borderRadius: 8,
    padding: '12px 16px',
    fontSize: 13,
    color: colors.textSubtle,
    lineHeight: 1.6,
  },
  code: {
    background: 'rgba(255,255,255,0.06)',
    padding: '1px 6px',
    borderRadius: 4,
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.primary,
  },
} satisfies Record<string, CSSProperties>
