import type { CSSProperties } from 'react'

export const colors = {
  bg: '#0c0c0f',
  surface: '#111116',
  surfaceElevated: '#16161d',
  surfaceHover: '#1c1c26',
  border: 'rgba(255,255,255,0.07)',
  borderStrong: 'rgba(255,255,255,0.12)',
  borderActive: '#6366f1',
  text: '#f0f0f2',
  textMuted: '#6b6b85',
  textSubtle: '#8a8ab0',
  accent: '#6366f1',
  accentHover: '#818cf8',
  accentSubtle: 'rgba(99,102,241,0.1)',
  accentBorder: 'rgba(99,102,241,0.25)',
  recording: '#f43f5e',
  recordingSubtle: 'rgba(244,63,94,0.08)',
  recordingBorder: 'rgba(244,63,94,0.2)',
  filled: 'rgba(99,102,241,0.05)',
  filledBorder: 'rgba(99,102,241,0.18)',
  warning: '#f59e0b',
  warningSubtle: 'rgba(245,158,11,0.06)',
  warningBorder: 'rgba(245,158,11,0.15)',
  error: '#f43f5e',
  errorSubtle: 'rgba(244,63,94,0.06)',
  errorBorder: 'rgba(244,63,94,0.18)',
}

export const styles = {
  container: {
    minHeight: '100vh',
    background: colors.bg,
    color: colors.text,
    fontFamily:
      '"Noto Sans JP", "Hiragino Kaku Gothic ProN", -apple-system, BlinkMacSystemFont, sans-serif',
  } satisfies CSSProperties,

  // ─── Header ───────────────────────────────────────────────
  header: {
    borderBottom: `1px solid ${colors.border}`,
    background: 'rgba(12,12,15,0.92)',
    backdropFilter: 'blur(12px)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  } satisfies CSSProperties,
  headerInner: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '0 24px',
    height: 52,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } satisfies CSSProperties,
  logoArea: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  } satisfies CSSProperties,
  logoIcon: {
    width: 24,
    height: 24,
    borderRadius: 6,
    background: colors.accent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 800,
    color: '#fff',
    letterSpacing: '-0.02em',
    flexShrink: 0,
  } satisfies CSSProperties,
  logoDivider: {
    width: 1,
    height: 18,
    background: colors.border,
  } satisfies CSSProperties,
  title: {
    margin: 0,
    fontSize: 15,
    fontWeight: 600,
    letterSpacing: '-0.01em',
    color: colors.text,
  } satisfies CSSProperties,
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 11,
    color: colors.textSubtle,
    fontFamily: 'ui-monospace, "JetBrains Mono", monospace',
    letterSpacing: '0.02em',
    padding: '5px 10px',
    borderRadius: 6,
    border: `1px solid ${colors.border}`,
    background: colors.surface,
  } satisfies CSSProperties,
  badgeDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: '#22c55e',
    boxShadow: '0 0 6px #22c55e',
  } satisfies CSSProperties,

  // ─── Layout ───────────────────────────────────────────────
  main: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '24px 24px 60px',
    display: 'grid',
    gridTemplateColumns: '1fr 440px',
    gap: 20,
    alignItems: 'start',
  } satisfies CSSProperties,
  leftCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,
  rightCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,

  // ─── Banners ──────────────────────────────────────────────
  statusBar: {
    padding: '10px 14px',
    background: colors.accentSubtle,
    border: `1px solid ${colors.accentBorder}`,
    borderRadius: 6,
    fontSize: 13,
    color: colors.accentHover,
    fontWeight: 500,
    letterSpacing: '-0.01em',
  } satisfies CSSProperties,
  errorBar: {
    padding: '10px 14px',
    background: colors.errorSubtle,
    border: `1px solid ${colors.errorBorder}`,
    borderRadius: 6,
    fontSize: 13,
    color: colors.error,
    fontWeight: 500,
  } satisfies CSSProperties,
  warningBar: {
    padding: '10px 14px',
    background: colors.warningSubtle,
    border: `1px solid ${colors.warningBorder}`,
    borderRadius: 6,
    fontSize: 13,
    color: colors.warning,
    lineHeight: 1.55,
  } satisfies CSSProperties,

  // ─── Stream preview ───────────────────────────────────────
  streamPreview: {
    background: colors.surface,
    border: `1px solid ${colors.accentBorder}`,
    borderLeft: `2px solid ${colors.accent}`,
    borderRadius: 6,
    padding: '10px 14px',
    maxHeight: 180,
    overflow: 'auto',
  } satisfies CSSProperties,
  streamPreviewLabel: {
    fontSize: 10,
    fontWeight: 600,
    color: colors.accent,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    marginBottom: 6,
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  streamPreviewBody: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.65,
    color: colors.text,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  } satisfies CSSProperties,
  streamCaret: {
    display: 'inline-block',
    color: colors.accent,
    animation: 'pulse-dot 0.9s ease-in-out infinite',
    marginLeft: 2,
  } satisfies CSSProperties,

  // ─── Model Panel ──────────────────────────────────────────
  modelPanel: {
    padding: '14px 16px',
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap' as const,
  } satisfies CSSProperties,
  modelPanelInfo: {
    flex: 1,
    minWidth: 260,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  } satisfies CSSProperties,
  modelSelectLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 10,
    fontWeight: 600,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  modelSelect: {
    flex: 1,
    minWidth: 200,
    background: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: '6px 10px',
    color: colors.text,
    fontSize: 13,
    outline: 'none',
    fontFamily: 'inherit',
    cursor: 'pointer',
    letterSpacing: '-0.01em',
  } satisfies CSSProperties,
  modelPanelNote: {
    fontSize: 12,
    color: colors.textSubtle,
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap' as const,
  } satisfies CSSProperties,
  modelPanelTitle: {
    fontWeight: 600,
    color: colors.text,
  } satisfies CSSProperties,
  progressBarOuter: {
    flex: 1,
    minWidth: 140,
    height: 2,
    borderRadius: 1,
    background: colors.border,
    overflow: 'hidden',
  } satisfies CSSProperties,
  progressBarInner: {
    height: '100%',
    background: colors.accent,
    transition: 'width 0.3s ease',
  } satisfies CSSProperties,

  // ─── Controls ─────────────────────────────────────────────
  controlGrid: {
    display: 'flex',
    gap: 8,
  } satisfies CSSProperties,
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '0 16px',
    height: 38,
    borderRadius: 6,
    border: '1px solid transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    transition: 'all 0.1s ease',
    position: 'relative',
    fontFamily: 'inherit',
    letterSpacing: '-0.01em',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  } satisfies CSSProperties,
  btnPrimary: {
    background: colors.accent,
    color: '#fff',
    border: `1px solid ${colors.accent}`,
  } satisfies CSSProperties,
  btnRecording: {
    background: colors.recording,
    color: '#fff',
    border: `1px solid ${colors.recording}`,
  } satisfies CSSProperties,
  btnAccent: {
    background: colors.accentSubtle,
    color: colors.accentHover,
    border: `1px solid ${colors.accentBorder}`,
  } satisfies CSSProperties,
  btnGhost: {
    background: 'transparent',
    color: colors.textSubtle,
    border: `1px solid ${colors.border}`,
  } satisfies CSSProperties,
  pulse: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.7)',
    animation: 'pulse-dot 1s ease-in-out infinite',
  } satisfies CSSProperties,

  // ─── Transcript ───────────────────────────────────────────
  transcriptSection: {
    background: colors.surface,
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    overflow: 'hidden',
  } satisfies CSSProperties,
  transcriptHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderBottom: `1px solid ${colors.border}`,
  } satisfies CSSProperties,
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: colors.textMuted,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  charCount: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: 'ui-monospace, monospace',
    letterSpacing: '0.02em',
  } satisfies CSSProperties,
  transcriptTextarea: {
    width: '100%',
    minHeight: 150,
    background: 'transparent',
    border: 'none',
    padding: '12px 0',
    color: colors.text,
    fontSize: 14,
    lineHeight: 1.8,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    boxSizing: 'border-box' as const,
  } satisfies CSSProperties,
  liveBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.1em',
    color: colors.recording,
    background: colors.recordingSubtle,
    border: `1px solid ${colors.recordingBorder}`,
    padding: '2px 7px',
    borderRadius: 4,
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  liveDot: {
    width: 4,
    height: 4,
    borderRadius: '50%',
    background: colors.recording,
    animation: 'pulse-dot 1s ease-in-out infinite',
  } satisfies CSSProperties,

  // ─── Form ─────────────────────────────────────────────────
  formHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  } satisfies CSSProperties,
  formTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: colors.textMuted,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    margin: 0,
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  formProgress: {
    fontSize: 11,
    color: colors.textMuted,
    fontFamily: 'ui-monospace, monospace',
    letterSpacing: '0.02em',
  } satisfies CSSProperties,
  fieldGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    background: colors.border,
    borderRadius: 8,
    overflow: 'hidden',
    border: `1px solid ${colors.border}`,
  } satisfies CSSProperties,
  fieldCard: {
    background: colors.surface,
    padding: '12px 16px',
    cursor: 'pointer',
    transition: 'background 0.1s ease',
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    minHeight: 48,
  } satisfies CSSProperties,
  fieldCardFull: {
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    minHeight: 64,
  } satisfies CSSProperties,
  fieldCardFilled: {
    background: colors.filled,
  } satisfies CSSProperties,
  fieldHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
    width: 90,
  } satisfies CSSProperties,
  fieldLabel: {
    fontSize: 12,
    fontWeight: 500,
    color: colors.textMuted,
    letterSpacing: '-0.01em',
    whiteSpace: 'nowrap' as const,
  } satisfies CSSProperties,
  filledDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: colors.accent,
    flexShrink: 0,
  } satisfies CSSProperties,
  fieldValue: {
    margin: 0,
    fontSize: 14,
    fontWeight: 400,
    color: colors.text,
    lineHeight: 1.5,
    flex: 1,
    letterSpacing: '-0.01em',
  } satisfies CSSProperties,
  fieldPlaceholder: {
    margin: 0,
    fontSize: 13,
    color: colors.textMuted,
    flex: 1,
    letterSpacing: '-0.005em',
  } satisfies CSSProperties,
  fieldInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    borderBottom: `1px solid ${colors.borderActive}`,
    padding: '2px 0',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box' as const,
    letterSpacing: '-0.01em',
  } satisfies CSSProperties,
  fieldTextarea: {
    width: '100%',
    background: 'transparent',
    border: 'none',
    borderBottom: `1px solid ${colors.borderActive}`,
    padding: '4px 0',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    boxSizing: 'border-box' as const,
    lineHeight: 1.6,
    marginTop: 4,
  } satisfies CSSProperties,

  // ─── Architecture ─────────────────────────────────────────
  archSection: {
    background: colors.surface,
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    padding: '14px 16px',
  } satisfies CSSProperties,
  archTitle: {
    margin: '0 0 12px',
    fontSize: 11,
    fontWeight: 600,
    color: colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  archFlow: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginBottom: 14,
    flexWrap: 'wrap' as const,
  } satisfies CSSProperties,
  archStep: {
    textAlign: 'center' as const,
    padding: '10px 12px',
    background: colors.surfaceElevated,
    borderRadius: 6,
    border: `1px solid ${colors.border}`,
    minWidth: 90,
  } satisfies CSSProperties,
  archStepIcon: {
    fontSize: 12,
    marginBottom: 4,
    color: colors.accent,
    fontFamily: 'ui-monospace, monospace',
  } satisfies CSSProperties,
  archStepLabel: {
    fontSize: 12,
    fontWeight: 600,
    marginBottom: 2,
    color: colors.text,
    letterSpacing: '-0.01em',
  } satisfies CSSProperties,
  archStepTech: {
    fontSize: 10,
    color: colors.textMuted,
    fontFamily: 'ui-monospace, monospace',
    letterSpacing: '0.02em',
  } satisfies CSSProperties,
  archStepDesc: {
    fontSize: 10,
    color: colors.textMuted,
    marginTop: 2,
  } satisfies CSSProperties,
  archArrow: {
    fontSize: 13,
    color: colors.textMuted,
    opacity: 0.5,
  } satisfies CSSProperties,
  archNote: {
    background: colors.surfaceElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: '10px 12px',
    fontSize: 13,
    color: colors.textSubtle,
    lineHeight: 1.6,
  } satisfies CSSProperties,
  code: {
    background: 'rgba(255,255,255,0.06)',
    padding: '1px 6px',
    borderRadius: 3,
    fontSize: 11,
    fontFamily: 'ui-monospace, monospace',
    color: colors.accentHover,
  } satisfies CSSProperties,
}
