// 元の monshin-assistant.jsx のスタイルオブジェクトを移植。
// Tailwind 等を使わずインライン style で動作させる。

import type { CSSProperties } from 'react'

export const colors = {
  bg: '#0a0f1a',
  surface: '#111827',
  surfaceHover: '#1a2236',
  border: '#1e293b',
  borderActive: '#3b82f6',
  text: '#e2e8f0',
  textMuted: '#64748b',
  primary: '#3b82f6',
  primaryDark: '#2563eb',
  accent: '#8b5cf6',
  accentDark: '#7c3aed',
  recording: '#ef4444',
  recordingDark: '#dc2626',
  success: '#10b981',
  filled: '#1e3a2f',
  filledBorder: '#065f46',
  warning: '#f59e0b',
}

export const styles = {
  container: {
    minHeight: '100vh',
    background: `linear-gradient(170deg, ${colors.bg} 0%, #0f172a 50%, #0c1220 100%)`,
    color: colors.text,
    fontFamily:
      '"Noto Sans JP", "Hiragino Kaku Gothic ProN", -apple-system, BlinkMacSystemFont, sans-serif',
  },
  header: {
    borderBottom: `1px solid ${colors.border}`,
    background: 'rgba(17, 24, 39, 0.8)',
    backdropFilter: 'blur(12px)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  headerInner: {
    maxWidth: 900,
    margin: '0 auto',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoArea: { display: 'flex', alignItems: 'center', gap: 12 },
  logoIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.accent})`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    fontWeight: 800,
    color: '#fff',
  },
  title: { margin: 0, fontSize: 18, fontWeight: 700, letterSpacing: '-0.02em' },
  subtitle: { margin: 0, fontSize: 12, color: colors.textMuted },
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 11,
    color: colors.success,
    background: 'rgba(16, 185, 129, 0.1)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    padding: '4px 10px',
    borderRadius: 20,
    fontWeight: 600,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: colors.success,
  },
  main: { maxWidth: 900, margin: '0 auto', padding: '20px 20px 60px' },
  statusBar: {
    padding: '10px 16px',
    background: 'rgba(59, 130, 246, 0.1)',
    border: '1px solid rgba(59, 130, 246, 0.2)',
    borderRadius: 10,
    fontSize: 13,
    marginBottom: 16,
    color: colors.primary,
    fontWeight: 500,
  },
  errorBar: {
    padding: '10px 16px',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: 10,
    fontSize: 13,
    marginBottom: 16,
    color: colors.recording,
    fontWeight: 500,
  },
  warningBar: {
    padding: '10px 16px',
    background: 'rgba(245, 158, 11, 0.08)',
    border: '1px solid rgba(245, 158, 11, 0.2)',
    borderRadius: 10,
    fontSize: 13,
    marginBottom: 16,
    color: colors.warning,
  },
  modelPanel: {
    padding: '14px 18px',
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: 12,
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  progressBarOuter: {
    flex: 1,
    minWidth: 160,
    height: 8,
    borderRadius: 4,
    background: 'rgba(59, 130, 246, 0.15)',
    overflow: 'hidden',
  },
  progressBarInner: {
    height: '100%',
    background: `linear-gradient(90deg, ${colors.primary}, ${colors.accent})`,
    transition: 'width 0.2s ease',
  },
  controlSection: { marginBottom: 20 },
  controlGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    gap: 10,
  },
  btn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    padding: '14px 8px',
    borderRadius: 12,
    border: '1px solid transparent',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 600,
    transition: 'all 0.15s ease',
    position: 'relative',
    fontFamily: 'inherit',
  },
  btnPrimary: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: '#fff',
    border: 'none',
  },
  btnRecording: {
    background: `linear-gradient(135deg, ${colors.recording}, ${colors.recordingDark})`,
    color: '#fff',
    border: 'none',
  },
  btnAccent: {
    background: `linear-gradient(135deg, ${colors.accent}, ${colors.accentDark})`,
    color: '#fff',
    border: 'none',
  },
  btnGhost: {
    background: colors.surface,
    color: colors.text,
    border: `1px solid ${colors.border}`,
  },
  btnIcon: { fontSize: 22 },
  pulse: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#fff',
  },
  transcriptSection: {
    background: colors.surface,
    borderRadius: 14,
    border: `1px solid ${colors.border}`,
    marginBottom: 20,
    padding: '14px 16px',
  },
  transcriptHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 8,
  },
  transcriptTextarea: {
    width: '100%',
    minHeight: 140,
    background: 'rgba(255,255,255,0.03)',
    border: `1px solid ${colors.border}`,
    borderRadius: 10,
    padding: '12px 14px',
    color: colors.text,
    fontSize: 15,
    lineHeight: 1.7,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical',
    boxSizing: 'border-box',
    transition: 'border-color 0.15s ease',
  },
  transcriptTextareaRecording: {
    borderColor: colors.recording,
    background: 'rgba(239, 68, 68, 0.04)',
  },
  liveBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.1em',
    color: colors.recording,
    background: 'rgba(239, 68, 68, 0.12)',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    padding: '2px 8px',
    borderRadius: 12,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: colors.recording,
    animation: 'pulse-dot 1s ease-in-out infinite',
  },
  streamPreview: {
    background: 'rgba(139, 92, 246, 0.06)',
    border: `1px solid ${colors.accent}33`,
    borderRadius: 10,
    padding: '10px 14px',
    marginBottom: 16,
    maxHeight: 180,
    overflow: 'auto',
  },
  streamPreviewLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.accent,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginBottom: 6,
  },
  streamPreviewBody: {
    margin: 0,
    fontSize: 12,
    lineHeight: 1.6,
    color: colors.text,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  streamCaret: {
    display: 'inline-block',
    color: colors.accent,
    animation: 'pulse-dot 0.9s ease-in-out infinite',
    marginLeft: 2,
  },
  sectionToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    background: 'transparent',
    border: 'none',
    color: colors.text,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 14,
    fontWeight: 700,
  },
  charCount: {
    fontSize: 11,
    color: colors.textMuted,
    background: 'rgba(100,116,139,0.15)',
    padding: '2px 8px',
    borderRadius: 10,
    fontWeight: 500,
  },
  chevron: {
    fontSize: 10,
    color: colors.textMuted,
    transition: 'transform 0.2s ease',
  },
  transcriptBody: {
    padding: '0 18px 16px',
  },
  transcriptText: {
    margin: 0,
    fontSize: 14,
    lineHeight: 1.8,
    color: colors.text,
  },
  interimText: {
    color: colors.primary,
    opacity: 0.7,
  },
  placeholder: {
    margin: 0,
    fontSize: 13,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  formSection: { marginBottom: 24 },
  formTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 12,
  },
  fieldGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
  },
  fieldCard: {
    background: colors.surface,
    borderRadius: 12,
    border: `1px solid ${colors.border}`,
    padding: '12px 14px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  fieldCardFull: { gridColumn: '1 / -1' },
  fieldCardFilled: {
    background: colors.filled,
    borderColor: colors.filledBorder,
  },
  fieldHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  fieldIcon: { fontSize: 14 },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  filledDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: colors.success,
    marginLeft: 'auto',
  },
  fieldValue: {
    margin: 0,
    fontSize: 14,
    fontWeight: 500,
    color: colors.text,
    lineHeight: 1.5,
  },
  fieldPlaceholder: {
    margin: 0,
    fontSize: 13,
    color: 'rgba(100,116,139,0.5)',
  },
  fieldInput: {
    width: '100%',
    background: 'rgba(255,255,255,0.05)',
    border: `1px solid ${colors.borderActive}`,
    borderRadius: 8,
    padding: '8px 10px',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  fieldTextarea: {
    width: '100%',
    background: 'rgba(255,255,255,0.05)',
    border: `1px solid ${colors.borderActive}`,
    borderRadius: 8,
    padding: '8px 10px',
    color: colors.text,
    fontSize: 14,
    outline: 'none',
    fontFamily: 'inherit',
    resize: 'vertical',
    boxSizing: 'border-box',
    lineHeight: 1.6,
  },
  archSection: {
    background: colors.surface,
    borderRadius: 14,
    border: `1px solid ${colors.border}`,
    padding: 20,
  },
  archTitle: {
    margin: '0 0 16px',
    fontSize: 13,
    fontWeight: 700,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  archFlow: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 4,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  archStep: {
    textAlign: 'center',
    minWidth: 90,
    padding: '10px 8px',
  },
  archStepIcon: { fontSize: 28, marginBottom: 6 },
  archStepLabel: { fontSize: 13, fontWeight: 700, marginBottom: 2 },
  archStepTech: {
    fontSize: 10,
    color: colors.primary,
    fontWeight: 600,
    fontFamily: 'monospace',
  },
  archStepDesc: { fontSize: 10, color: colors.textMuted, marginTop: 2 },
  archArrow: {
    fontSize: 20,
    color: colors.textMuted,
    opacity: 0.4,
    marginTop: 16,
  },
  archNote: {
    background: 'rgba(139, 92, 246, 0.08)',
    border: '1px solid rgba(139, 92, 246, 0.15)',
    borderRadius: 10,
    padding: '12px 16px',
    fontSize: 13,
    color: colors.text,
  },
  code: {
    background: 'rgba(59, 130, 246, 0.15)',
    padding: '1px 6px',
    borderRadius: 4,
    fontSize: 12,
    fontFamily: 'monospace',
    color: colors.primary,
  },
} satisfies Record<string, CSSProperties>
